name: Unit tests workflow
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  Get-CI-Image-Tag:
    uses: opensearch-project/opensearch-build/.github/workflows/get-ci-image-tag.yml@main
    with:
      product: opensearch-dashboards

  build-and-test:
    name: Run unit tests
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set env
        run: |
          opensearch_version=$(node -p "require('./opensearch_dashboards.json').opensearchDashboardsVersion")
          major_version=$(echo $opensearch_version | cut -d. -f1)
          minor_version=$(echo $opensearch_version | cut -d. -f2)
          branch_version=${major_version}.${minor_version}
          opensearch_dashboards_branch=$branch_version
          base_branch=${{ github.base_ref }}
          if [ "$base_branch" = "main" ]; then
            opensearch_dashboards_branch=main
          fi
          echo "OPENSEARCH_DASHBOARDS_BRANCH=$opensearch_dashboards_branch" >> $GITHUB_ENV
        shell: bash
      - name: Enable longer filenames
        if: ${{ matrix.os == 'windows-latest' }}
        run: git config --system core.longpaths true
      - name: Checkout OpenSearch-Dashboards
        uses: actions/checkout@v4
        with:
          repository: opensearch-project/OpenSearch-Dashboards
          ref: ${{ env.OPENSEARCH_DASHBOARDS_BRANCH }}
          path: OpenSearch-Dashboards
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: './OpenSearch-Dashboards/.nvmrc'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Yarn
        shell: bash
        run: |
          YARN_VERSION=$(node -p "require('./OpenSearch-Dashboards/package.json').engines.yarn")
          echo "Installing yarn@$YARN_VERSION"
          npm i -g yarn@$YARN_VERSION
      - run: node -v
      - run: yarn -v
      - name: Checkout dashboards-maps plugin
        uses: actions/checkout@v4
        with:
          path: OpenSearch-Dashboards/plugins/dashboards-maps
      - name: Bootstrap plugin/OpenSearch-Dashboards
        run: |
          cd OpenSearch-Dashboards/plugins/dashboards-maps
          yarn osd bootstrap
      - name: Run unit tests
        run: |
          cd OpenSearch-Dashboards/plugins/dashboards-maps
          yarn run test:jest --coverage
      - name: Uploads coverage
        uses: codecov/codecov-action@v1
